export const VERSETS = [
	{
		id:0,
		titre: "Introduction",
		libele: "Peu importe le temps, dans la cité du Salam, les habitants se devaient plus que de l’appartenance. Il faut toujours une main basse, un œil envouté, un chemin escompté par le sage pèlerin de la Mecque. Notre sage aux connaissances idylliques se faisait connaître par ses divers talents maraboutiques et sa notoriété légitimement ancrée dès son plus jeune-âge. Moussa, Diadié et Boubacar étaient des descendants de vieilles connaissances. Comme on dit souvent « une belle eau ne reste pas longtemps dans le canari ». L’adage avait tout de même fait son apparition aux grandes portes de la maison royale, le chef de cette contrée était très charitable et il avait une grande qualité en matière de gestion coutumière et le vivre ensemble. Un jour, il se passait quelque chose de très différent, des rumeurs soulignaient au chef que quelque chose de très nouveau se préparait dans la cité. Une cité, qui ne connaissait que la paix, le partage et la fête. Connue du voisinage comme la cité de la danse traditionnelle. Une notoriété que toutes les différentes souches ethniques partageaient de loin. Fort de caractère (chef de la cité), il annonçait une réunion dans sa demeure pour étayer ses facettes et son vécu en tant qu’enfant héritière de cette cité. Un discours un peu énigmatique où il commençait par ce fameux passage Abrahamique : « Qui va vraiment me juger pour la probation à ma nouvelle requête ? J'étais et je suis, mais je serai selon le jugement que tu porteras sur moi. Le vieux sage, le vieux fou regardait, voyait voler, criant haut et fort d'un travail pourvu de tout temps, des éloges aux étés juteux, des récompenses aux passés et d'inspiration aux grands activistes pour une nouvelle société pour la nôtre. On l'aimait mais on voulait la changer pour être à jour, continuer de rayonner pour ses frères et sœurs, l'amour solidaire qui existait au jour et une nuit, tout était si fort et si partagé. Aujourd'hui, nous sommes des enfants qui rêvent d'un avenir singulier. Est-il possible de dire qu'on était pour un jour futur ? ». Le discours du chef de la cité du Salam donnait une réelle posologie de la genèse de la cité à travers des millénaires. "
	},
	{	id:1,
		titre: "Crépûscule de la cité antique",
		libele: "Au crépuscule, la cité ne protégeait pas que les troupeaux mais bien encore, elle protégeait également ses poussins de clivages de contorsions ethniques. Puisqu’il s’agissait des longs mûrissements, les jambes endiablées de la déesse résonnaient depuis l’entrée principale. Diadié et son oncle aimaient se distraire de la vérité ambiguë car, sceptique et d’emblée l’extrême vaillance que leurs géniaux ont octroyés la déesse bien avant l’avancée du vent de l’Atlantique. Les mots n’en finissaient pas dans la cité puisqu’au fond du gouffre, les mamelles n’eussent que des remords aux aléas de la vie sans espoir. Les maux avaient un sens pour ses enfants de l’autre bout du monde. Ils croyaient en quelque chose d'apaisant mais là encore, la déglutination depuis la bouée de l’eau salée ajoutait dans leurs imaginaires respectifs une randonnée de suspicion à la face ancestrale. L’objectif du début n’était plus de ce qu’il aurait goûté sur la terre gauloise. Quelle ardeur mais mince quelle vérité ! Diadié voit son oncle éternuer, il lui secoue quelques muettes invocations pour assouvir. Délétère, il mettait l’espoir existentiel pour faire du grand espoir une montagne d’or. En ce temps-là, la farce identitaire battait son plein au pays. Moussa se résilie sur deux branches d’arbres. L’une pour chercher l’appartenance idéologique et l’autre pour combler l’appartenance ancestrale. Deux horizons complémentaires et à la fois contradictoires. La culture ancestrale, pour lui, doit-il nouer aux origines ou d’en dissuader l’idéologie interprétée ou transmise ? N'est-il pas un membre éclairé de la voie orale ou la religiosité par la grande traversée finissait par détourner du droit chemin ? Tout ce que l’on sait, c'est que ces deux branches sont pour la complétude de l’humain. Son oncle qui a été gommé et circoncis par le grand marabout avait une dette envers son maître… Peu importe ce qui se passait aux dépendances, la terre gauloise n’excuse en rien la paresse et l’inaction.  "
	},
	{
		id:2,
		titre : "CAMARA Daouda : Voyage vers la terre promise",
		libele : " Le jeune héritier avait déjà fait un long chemin pour parvenir à se séparer de l’inébranlable car, depuis tout jeune, il avait une curiosité envers les transmissions des principes d’asservissement intellectuel. Croisé l’européen tout au long de sa quête permettait à la terre du Salam d’avoir des yeux qui ne se contentent pas de près. Il se muait vent et terre pour trouver des réponses à ses questions bouleversantes. En dépit de ce manque de preuve formelle, il se hissait et méditait souvent pour que la croisade avec celui qui est soit enfin vu le jour. Comment croire à ce qui lui est impossible de voir ? Comment se remettre à une existentielle dotée de mystique et d’espoir, qui hélas ne saurait que partiel ? La partialité divine pour les générations y ou z est humoristique car en croyant aux sciences et à la modernité diffusée, certains jaugent le baromètre de la connaissance des ancêtres comme étant révolue. Il faudrait en finir pour ne pas dire se fatiguer des cours de répétition. Il disait à son oncle qu’il va prendre l’absence comme un doute et essayer de construire une idée première à ce qui résonnait dans son fort conscient. Sceptique et nul sait que les doutes font craindre à la foi. Sans foi, l’être se retrouve dans un bouleversement séquentiel où il demeure parfois immobile. L’arrivée du vent de la terre gauloise suscite d’innombrables questions pour la cité et de sa constitution puisque la nécessité d’un changement ne se débattait pas pour d’autres. Mais sous l’angle du silence, toute forme de justice contre la volonté des notables noctambules était d’une folie ancestrale. Le vieux avec une généalogie tracée depuis notre Père Adam ne donnait crédit à quiconque qui veut détrôner. L’espoir est une force pour quelqu’un qui survit car, au comble des doutes, les choix des départs étant jadis des obligations pour une grande majorité de ses rescapés identitaires. "
	},
	{
		id:3,
		titre : "Nessus : l'animal de la cavalière",
		libele : "Nessus ! Aux galopes, Oh Nessus ! Une corpulence friandise et une ouïe tournée vers la séduction. Il aura fallu une décennie pour ressortir ton œil de ce détour. Pourvu que mon éloignement fût ta croissance, les cieux congédient pour la rencontre sublime. À l’horizon, on l’eut cru d’une centaure dépaysé de la coloration tropicale. On milieu des rivières garnies, tu regorgeais ta douceur hivernale telle une femme méduse. Auprès de ta joue, Monsieur le fou enfoui, tirait son chapeau argenté pour n’entendre que ta voix complice. Pour Nessus, tous les hivers étaient dorés. Aux premières gouttes, ton regard nous emparait du néant. Le vieux fou s'empresse de choisir la direction au surcroît de ton regard à l´horizon. L’unicité, une originalité était ce hurlement contingent. Avec ta compagnie en cette terre de paix, l’hiver donnait ses soins naturels et des nèfles pour redonner ton regard palliatif. Nessus était sceptique quant à la difformité des hectares déboisés. A des exceptions près, Nessus ressemblait à la déesse de part sa loyauté envers son maitre, à la belle prétendante de part sa beauté animalière, à l’oncle de Diadié de part sa doléance à la conformité d’antan et de notre grand marabout de part son appétence de la connaissance des faits. Difficile de trouver surprise pour quelqu’un qui, autour d’un café souhaite partager votre manière d’être et d’opter de fusionner dans la gélification cellulaire l’existentialisme des miennes aux siennes. Fervent et serein de l’engagement coutumière, il aura fallu une réelle cogitation pour la laisser passer comme une guerre sans défaite. Ce combat fût et restera pour demain car, comme le cœur ne saurait réussir à oublier qu’une infirme afflux de sang affectif. Comme le jour et comme la nuit, j’étais obnubilé de ta douceur frontalière et ta franchise envers nous. Tout était un cheminement des découvertes entre Aquitaine et l’Alsace Lorraine. Douces et gentils étaient leurs franchises les habitants de l’Alsace Lorraine et neutres et reconnaissants étaient les habitants du vin pur. Tout se consumait quand les regards sont complices entre deux individus qui, sur la suite mystère et l’espoir de gagner une bataille de conquête. Enfin un espoir et une exception heureuse. Aux circonstances de la vie, Diadié devait ajuster son nivellement orgasmique. De surcroît de cette aventure jalonnée des mœurs, Diadie devait à l’incognito se divertir des dimanches entre découvertes et surprises à la gare Part-Dieu."
	}


]